version: 2.1
jobs:
  push-source:
    docker:
      - image: google/cloud-sdk:283.0.0
    steps:
      - checkout
      - run:
          name: Activate Service Account
          command: |
            echo ${SERVICE_ACCOUNT} > /tmp/key.json
            gcloud auth activate-service-account --key-file /tmp/key.json
      - run:
          name: Add git repository
          command: |
            git remote add google ${REPOSITORY_URL}
            git config --global credential.https://source.developers.google.com.helper gcloud.sh
      - run: git push -f google master
workflows:
  push-source:
    jobs:
      - push-source
